config/routes.rb
Rails.application.routes.draw do
  get 'restricted_access/restricted_user'

  devise_for :users
  get 'home/index'

  root to: 'home#index'

  namespace :admin do
   root 'home#index'
   resources :services
   get 'user_validation', to: 'validations#index', as: "user_validation"
   get 'show_user_validation/:id', to: 'validations#show', as: "show_user_validation"
   post 'validate_user', to: 'validations#validate_user', as: 'validate_user'
  end

  resources :services, only: [:index, :show]
  post 'suscribe', to: 'services#suscribe', as: 'suscribe'
  get 'unsuscribe/:id/:service_id', to: 'services#unsuscribe', as: 'unsuscribe'
 

end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :suscriptions, dependent: :destroy
end

app/models/suscription.rb
class Suscription < ActiveRecord::Base
	belongs_to :service
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
	class BaseController < ApplicationController
	before_action :authenticate_user!
	before_action :require_admin
	
	private
	  def require_admin
	  	redirect_to root_path, notice: "No eres Admin" unless current_user.admin
	  end
	end
end

app/controllers/admin/home_controller.rb
module Admin
	class HomeController < BaseController
	  def index
	  end
	end
end

app/controllers/admin/services_controller.rb
module Admin
  class ServicesController < BaseController
    before_action :set_service, only: [:show, :edit, :update, :destroy]

    def index
      @services = Service.all
    end

    def show
    end

    def new
      @service = Service.new
    end

    def edit
    end

    def create
      @service = Service.new(service_params)

      respond_to do |format|
        if @service.save
          format.html { redirect_to [:admin,@service], notice: 'Service was successfully created.' }
          format.json { render :show, status: :created, location: @service }
        else
          format.html { render :new }
          format.json { render json: @service.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @service.update(service_params)
          format.html { redirect_to [:admin,@service], notice: 'Service was successfully updated.' }
          format.json { render :show, status: :ok, location: @service }
        else
          format.html { render :edit }
          format.json { render json: @service.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @service.destroy
      respond_to do |format|
        format.html { redirect_to admin_services_url, notice: 'Service was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_service
        @service = Service.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def service_params
        params.require(:service).permit(:name, :description, :price)
      end
  end
end

app/controllers/admin/validations_controller.rb
module Admin
  class ValidationsController < BaseController
    before_action :set_validation, only: [:show, :update]


    def index
      # @validations = User.where(["validated = ?", 0]).pluck(:id)
      @validations = User.all
    end


    def show
      @validation =  User.find(params[:id]) 
      @new_user = User.new()
    end

    def validate_user
      
      @user = User.find(params[:user][:id])
      
      respond_to do |format|
        if @user.update(validated: params[:user][:validated])
          format.html { redirect_to admin_user_validation_path, notice: 'Se valido el usuario.' }
          # format.json { render :show, status: :ok, location: @validation }
        else
          format.html { render "index" }
          # format.json { render json: @validation.errors, status: :unprocessable_entity }
        end
      end

    end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_validation
        @validation = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def validation_params
        params[:validation]
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/restricted_access_controller.rb
class RestrictedAccessController < ApplicationController
  def restricted_user
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show]
  before_action :check_validated_user

  def index
    @services = Service.all
#     @suscriptions = Suscription.where(["user_id = ?", current_user.id]).pluck(:id)
#     @services = Service.where(:id => 'Entrevista')
# raise
#       @survey_data = Survey.where(:survey_type => 'Entrevista').order('random()').first
#     unless @survey_data.nil?
#       redirect_to show_job_interview_survey_path(data_id: @survey_data.id)
#     end
  end

  def show
    @service =  Service.find(params[:id]) 
    @suscription = Suscription.where(["user_id = ? AND service_id = ? ", current_user.id, params[:id]]).pluck(:id)
    @new_suscription = Suscription.new
  end

  def suscribe
    @suscription = Suscription.new(service_id: params[:suscription][:service_id], user_id: params[:suscription][:user_id])
    if @suscription.save
      redirect_to service_path(params[:suscription][:service_id]), notice: "Se ha suscrito a este servicio."
    else
      flash.now[:alert] = "Se produjo un error , intente de nuevo"
      render "show"
    end
  end

  def unsuscribe
    # service = Suscription.where(["id = ?",]).pluck(:service_id)
    suscription = Suscription.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to service_path(params[:service_id]), notice: 'Se ha desuscrito del servicio' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    def check_validated_user
      if(!current_user.validated)
        redirect_to controller: "restricted_access", action:"restricted_user"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restricted_access_helper.rb
module RestrictedAccessHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/validations_helper.rb
module ValidationsHelper
end

app/views/admin/home/index.html.erb
Hola Administrador
<br>
<%= link_to 'Administrar Servicios',admin_services_path ,:class => "btn btn-primary" %>
<br>
<%= link_to 'Validar Usuarios',admin_user_validation_path ,:class => "btn btn-primary" %>

app/views/admin/services/_form.html.erb
<%= form_for([:admin, @service]) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @service] %> |
<%= link_to 'Back', admin_services_path %>

app/views/admin/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.price %></td>
        <td><%= link_to 'Show', [:admin, service] %></td>
        <td><%= link_to 'Edit', edit_admin_service_path(service) %></td>
        <td><%= link_to 'Destroy', [:admin, service], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_admin_service_path %>

app/views/admin/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_services_path %>

app/views/admin/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>

<%= link_to 'Edit', edit_admin_service_path(@service) %> |
<%= link_to 'Back', admin_services_path %>

app/views/admin/validations/_form.html.erb
<%= form_for([:admin, @validation]) do |f| %>
  <% if @validation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@validation.errors.count, "error") %> prohibited this validation from being saved:</h2>

      <ul>
      <% @validation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/validations/edit.html.erb
<h1>Editing Validation</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @validation] %> |
<%= link_to 'Back', admin_validations_path %>

app/views/admin/validations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Validations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @validations.each do |validation| %>
      <tr>
        <% if !validation.validated %>
        <td><%= validation.email  %></td>
        <td><%= validation.validated  %></td>
        <td><%= link_to 'Show', admin_show_user_validation_path(validation.id) %></td>
        <td><%#= link_to 'Edit', edit_admin_validation_path(validation) %></td>
        <td><%#= link_to 'Destroy', [:admin, validation], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Validation', new_admin_validation_path %>

app/views/admin/validations/new.html.erb
<h1>New Validation</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_validations_path %>

app/views/admin/validations/show.html.erb
<p id="notice"><%= notice %></p>
<%= @validation.email %>
<%= @validation.validated %>

<%= simple_form_for @new_user, url: admin_validate_user_path do |f| %> 
  <%= f.input :validated, as: :hidden, id: "status", input_html: { value: 1 }  %>
  <%= f.input :id, as: :hidden, id: "status2", input_html: { value: @validation.id }  %>
	<br>
	<%= f.submit "Validar" %> 
<% end %>

<%#= link_to 'Edit', edit_admin_validation_path(@validation) %> |
<%= link_to 'Back', admin_user_validation_path %>

app/views/home/index.html.erb
<h2>Hola Usuario</h2>

<br>
<%= link_to 'Ver Servicios',services_path ,:class => "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <title>IT On Demand!!!</title> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">IT On Demand!!!</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

   <%= render 'partials/jumbotron' %>

    <div class="container">
      <%= yield %>

      <hr>


    </div> <!-- /container -->

    <%= render 'partials/footer' %>

</body>
</html>

app/views/partials/_footer.html.erb
      <footer>
        <p>&copy; It On Demand 2016</p>
      </footer>

app/views/partials/_jumbotron.html.erb
 <!-- Main jumbotron for a primary marketing message or call to action -->
  </div> 
    <div class="jumbotron">
      <div class="container">
        <div class= "rectangle"><h1>IT On demand!!!</h1></div>
        <div id ="user_nav">
			    <% if user_signed_in? %>
			      Signed in as <%= current_user.email %>. Not you?
			      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			    <% else %>
			      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
			    <% end %>
			  </div>
        <!-- <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p> -->
    </div>

app/views/restricted_access/restricted_user.html.erb
<h1>Acceso restringido, debe esperar a que un admin haya validado su cuenta</h1>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td>$<%= service.price %></td>
        <td><%= link_to 'Show', service %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>


<%#= form_for(@service) do |f| %> 
<% if @suscription[0].nil? %>

	<%= simple_form_for @new_suscription, url: suscribe_path do |f| %> 
	  <%= f.input :service_id, as: :hidden, id: "service", input_html: { value: @service.id }  %>
	  <%= f.input :user_id, as: :hidden, id: "user", input_html: { value: current_user.id }  %>
	<%= f.submit "Suscribirse" %> 
	<% end %>

<% else %>
	<%= link_to 'Desuscribirse', unsuscribe_path(@suscription, @service.id),:class => "btn btn-primary", data: { confirm: 'Seguro que desea desuscribirse?' } %>


<% end %>
	<br>
	<br>



<%= link_to 'Back', services_path %>